apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-backend-deployment
  labels:
    app: school-backend-deployment

spec:
  selector:
    matchLabels:
      app: school-backend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: school-backend-deployment
    spec:
      containers:
        - name: school-backend-container
          image: docker.io/sherifemad21/school-backend:v2
          ports:
            - containerPort: 8081
          env: # Setting Enviornmental Variables
            - name: DB_ADDRESS 
              value: school-database-service
            - name: DB_PORT 
              value: "3307"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD 
              value: root
            - name: DB_NAME 
              value: school_db

---
apiVersion: v1 
kind: Service
metadata: 
  name: school-backend-service
spec:
  type: NodePort
  selector:
    app: school-backend-deployment
  ports:
    - port: 8081 # The port that the service is running on in the cluster
      targetPort: 8081 # The port exposed by the service
      protocol: TCP
      nodePort: 32000  
  
