apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-backend-deployment-prod
  labels:
    app: school-backend-deployment-prod

spec:
  selector:
    matchLabels:
      app: school-backend-deployment-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: school-backend-deployment-prod
    spec:
      containers:
        - name: school-backend-container-prod
          image: DockerImageToPull
          ports:
            - containerPort: 8081

---
apiVersion: v1 
kind: Service
metadata: 
  name: school-backend-service-prod
spec:
  type: NodePort
  selector:
    app: school-backend-deployment-prod
  ports:
    - port: 8081 # The port that the service is running on in the cluster
      targetPort: 8081 # The port exposed by the service
      protocol: TCP
      nodePort: 32000  
  
