apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-backend-deployment-dev
  labels:
    app: school-backend-deployment-dev

spec:
  selector:
    matchLabels:
      app: school-backend-deployment-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: school-backend-deployment-dev
    spec:
      containers:
        - name: school-backend-container
          image: DockerImageToPull
          ports:
            - containerPort: 8081

---
apiVersion: v1 
kind: Service
metadata: 
  name: school-backend-service-dev
spec:
  type: NodePort
  selector:
    app: school-backend-deployment-dev
  ports:
    - port: 8081 # The port that the service is running on in the cluster
      targetPort: 8081 # The port exposed by the service
      protocol: TCP
      nodePort: 31000  
  
